<a href="https://colab.research.google.com/github/peraltarh/VIUMasterInAI/blob/main/2.Python%20para%20la%20inteligencia%20artificial/Paper/Whitepaper_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduccion

El articulo analizado presenta una comparativa entre el proceso de Indexing, Copia y Slicing utilziando NumPy Arrays.
A continuacion se presentara un resumen del ariculo y un analisis de sus concluciones.

# Analysis detallado

TBD

In [ ]:
#Analsis del codigo propuesto y desarrollo personal

# Indexado de Arrays

# Indexado de enteros
X = [3,1,4,1,5,9,2,6]
print(X[-2]) # Al introducir un numero negativo, se cuenta desde el final de la lista
print(X[3])

Y = [[3,1,4,1],[5,9,2,6]]
print(Y[0][2])
print(Y[-1][2]) # Nuevamente, al introducir un numero negativo, se cuenta desde el final de la lista

# Indexado de Booleans
import numpy as np
Y_np = np.array(Y)
y1 = Y_np > 3
print(y1) # Devuelve un array de booleanos, donde True indica que el elemento es mayor que 3
print(Y_np[y1]) # Devuelve los elementos de Y que son mayores que 3

# Indexado Sofisticado
import numpy as np
X_np = np.array(X)
x1 = X_np[[0, 3, 4]] # Devuelve un nuevo array con los elementos en las posiciones 0, 3 y 4 de X_np
print(x1)
print(X_np[[1, 1]])
print(X_np[[2, 3]]) # Devuelve un nuevo array con los elementos en las posiciones 2 y 3 de X_np])

# x2 = X[np.array([1,1],[2,3])] # Esta línea no es válida, ya que np.array espera un array de una sola dimensión o una lista de listas
x2 = np.array([[X[1], X[1]], [X[2], X[3]]])
print(x2)

# Indexado de Arrays con múltiples dimensiones
# print (Y[np.array([0,-1)]), np.array([1,2)])]) # No es valido
y2 = np.array([Y[0][-1], Y[1][2]])
print(y2) 

# Relacion entre Indexado y copias

x3 = X.copy() #En este caso esto equivale a deep copy, creando una copia independiente de X

# Analisis de como la copia afecta el indexado 
print(x3 is X) # Output: False
print(id(X)) 
print(id(x3)) # Son diferentes objetos en memoria
print(X)
print(x3)

X[0]=6 # Modificando X no afecta a x3
print(X)
print(x3)

y2=[Y[0][-1],Y[1][2]] # En el papar pone Y[[0,-1],[1,2]] pero no finciona.
y2[1]=666 # Modificando y2 no afecta a Y
print(y2)
print(Y)

# Array Slicing (TBD)




2
1
4
2
[[False False  True False]
 [ True  True False  True]]
[4 5 9 6]
[3 1 5]
[1 1]
[4 1]
[[1 1]
 [4 1]]
[1 2]
False
2082081533888
2082323330048
[3, 1, 4, 1, 5, 9, 2, 6]
[3, 1, 4, 1, 5, 9, 2, 6]
[6, 1, 4, 1, 5, 9, 2, 6]
[3, 1, 4, 1, 5, 9, 2, 6]
[1, 666]
[[3, 1, 4, 1], [5, 9, 2, 6]]


# Opinion personal del articulo

TBD -- Tuve que corregir bastante el codigo de los ejemplos

# Referencias

[1] A. A. S. de Oliveira, J. C. S. dos Santos, and J. M. de Araújo, "A study on Fibonacci sequence and its applications," Journal of Physics: Conference Series, vol. 2832, no. 1, p. 012019, 2021. [Online]. Disponible: https://iopscience.iop.org/article/10.1088/1742-6596/2832/1/012019